Repository os-climate/aicoe-osc-demo, pull requests merged in 2022-08, with the labels that each got.

#195 Add a settings file to tweak the demo
  notebooks/demo2/config.py
  notebooks/demo2/config_farm_train.py
  notebooks/demo2/config_qa_farm_train.py
  notebooks/demo2/inference.pipeline
  notebooks/demo2/settings.yaml
  notebooks/demo2/training.pipeline
Labels: size/L, approved, lgtm

#190 Add new diagram
  docs/assets/demo2-viz-v1.png
  docs/assets/demo2-viz.png
Labels: approved, lgtm, size/XS

#194 Benchmarking Script for both Relevance and KPI Inference Models
  notebooks/demo2/benchmarks.ipynb
Labels: size/XXL, approved, lgtm, benchmark

#196 Add pdf selection workflow
  data/kpi_mapping/kpi_mapping.csv
  notebooks/demo2/config.py
  notebooks/demo2/infer_relevance.ipynb
  notebooks/demo2/settings.yaml
  notebooks/demo2/setup_experiments_default_pdfs.ipynb
  notebooks/demo2/setup_experiments_select_pdfs.ipynb
Labels: size/XL, approved, lgtm
