Repository os-climate/aicoe-osc-demo, pull requests merged in 2022-11, with the labels that each got.

#230 Updated owners file
  OWNERS
Labels: approved, lgtm, size/XS

#227 Update the repository for creating access issues
  docs/access-jh.md
Labels: approved, lgtm, size/XS

#216 Add transformer implementation of relevance task
  notebooks/demo2/transformer-relevance.ipynb
  notebooks/demo2/transformer_inference.ipynb
  reports/benchmarks/distilbert_relevance.pkl
Labels: size/XXL, approved, lgtm

#214 Add performance benchmark notebook
  notebooks/demo2/benchmarks_performance.ipynb
  notebooks/demo2/train_kpi_extraction.ipynb
  notebooks/demo2/train_relevance.ipynb
Labels: size/XXL, approved, lgtm

#217 Add time analysis notebook and dataframe
  notebooks/demo2/time-anlysis.ipynb
  reports/benchmarks/kpi_metrics_df.pkl
  reports/benchmarks/metrics_df.pkl
Labels: size/XXL, approved, lgtm

#235 Add osc-ingest-tools to pipfile
  Pipfile
  Pipfile.lock
Labels: size/XXL, approved, lgtm

#242 Update dockerfile with latest image
  Dockerfile
Labels: approved, lgtm, size/XS

#243 Revert "Add osc-ingest-tools to pipfile"
  Pipfile
  Pipfile.lock
Labels: size/XXL

#234 Add notebook for Sparse models
  notebooks/demo2/transformer-inference-sparse.ipynb
  notebooks/demo2/transformer-relevance-sparse.ipynb
Labels: size/XXL, approved, lgtm
