Repository os-climate/aicoe-osc-demo, pull requests merged in 2022-04, with the labels that each got.

#144 Remove s3c from kpi-mapping.py
  Pipfile
  Pipfile.lock
  notebooks/demo2/config.py
  notebooks/demo2/infer_kpi.ipynb
  notebooks/demo2/infer_relevance.ipynb
  notebooks/demo2/pdf_text_curation.ipynb
  notebooks/demo2/pdf_text_extraction.ipynb
  src/components/__init__.py
  src/components/preprocessing/__init__.py
  src/components/preprocessing/curator.py
  src/components/preprocessing/text_curator.py
  src/components/utils/kpi_mapping.py
  src/models/__init__.py
  src/models/relevance_infer.py
  src/models/text_kpi_infer.py
Labels: size/XXL

#147 Downgrade markupsafe to fix soft_unicode deprecation error.
  Pipfile
  Pipfile.lock
Labels: size/XL

#148 Update table curator to work w changes in kpi mapping utils.
  src/components/preprocessing/table_curator.py
Labels: size/S, lgtm
