Repository os-climate/aicoe-osc-demo, pull requests merged in 2022-10, with the labels that each got.

#212 Remove pipfile-requirements manager from .thoth.yaml
  .thoth.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#208 Update benchmarks.ipynb
  notebooks/demo2/benchmarks.ipynb
Labels: size/XXL, approved, lgtm

#219 Adjusted envorinment variable names
  notebooks/demo2/create_results_table.ipynb
  notebooks/demo2/infer_kpi.ipynb
  notebooks/demo2/infer_relevance.ipynb
  notebooks/demo2/pdf_text_extraction.ipynb
  notebooks/demo2/setup_experiments_default_pdfs.ipynb
Labels: size/XXL, approved, lgtm

#225 Changed the environment variable name to original in order to match with elyra pipeline
  notebooks/demo2/create_results_table.ipynb
  notebooks/demo2/infer_kpi.ipynb
  notebooks/demo2/infer_relevance.ipynb
  notebooks/demo2/pdf_text_extraction.ipynb
  notebooks/demo2/setup_experiments_default_pdfs.ipynb
Labels: approved, lgtm, size/M
